# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Colorado Mountain History Collection'
description:      'Historic photographs from the CMHC and LCPL collections, Leadville City Directories, Leadville City Jail records, digitized documents, maps, video and audio recordings, and other items that represent the changes of Leadville and Lake County through time'
url:              'https://history.lakecountypubliclibrary.org'
baseurl:          '/cmhc'
copyright:        'Copyright Lake County Public Library, 2020'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: true
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  cmhc: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'cmhc_item' # the layout for the pages to use
    metadata:
      source: 'cmhc.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/cmhc' # path to the directory of images within `_data`
  directories: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'cmhc_item' # the layout for the pages to use
    metadata:
      source: 'directories.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/directories' # path to the directory of images within `_data`
  census: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'cmhc_item' # the layout for the pages to use
    metadata:
      source: 'census.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/census' # path to the directory of images within `_data`


# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      cmhc:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - creation_date
          - format
          - keywords
          - description
          - named_persons
          - source
          - rights
          - pid
  directories:
    index: '/search/directories.json' # file the index will get written to
    collections:
      directories:
        content: false
        fields:
          - keywords
          - description
          - text
          - pid
  census:
    index: '/search/census.json' # file the index will get written to
    collections:
      census:
        content: false
        fields:
          - keywords
          - description
          - text
          - pid

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:  
  - label: 'Home'
    link: '/'
  - label: 'Browse Collections'
    sub:
      - label: 'Buildings & Businesses'
        link: '/bandb/'
      - label: 'Climax'
        link: '/climax/'
      - label: 'Leadville'
        link: '/leadville/'
      - label: 'Mining'
        link: '/mining/'
      - label: 'Outside Lake County'
        link: '/outside/'
      - label: 'People'
        link: '/people/'
      - label: 'Railroad Images'
        link: '/rail/'
      - label: 'Twin Lakes'
        link: '/twin/'
      - label: 'Documents & Objects'
        link: '/docs/'
      - label: 'Uncategorized'
        link: '/uncat/'
  - label: 'Map'
    link: '/map/'
  - label: 'Search'
    link: '/search/'
  - label: 'About'
    sub:
      - label: 'Contact'
        link: '/contact/'
      - label: 'Feedback'
        link: '/feedback/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/lake-county-public-library'
    - label: 'Contact'
      link: '/contact'
    - label: 'Lake County Public Library'
      link: 'https://www.lakecountypubliclibrary.org/'
  logos:
    - img: '/img/logo.png'

# --------------------------------------------------------------
# GOOGLE ANALYTICS SETTINGS
# --------------------------------------------------------------
google_analytics: G-426Y3GLHWW

# FIN
