# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'CMHC'
description:      'Historic photographs from the CMHC and LCPL collections, Leadville City Directories, Leadville City Jail records, digitized documents, maps, video and audio recordings, and other items that represent the changes of Leadville and Lake County through time'
url:              'http://history.lakecountypubliclibrary.org'
baseurl:          '/cmhc'
copyright:        'Copyright Lake County Public Library, 2020'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  leadville: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'leadville_item' # the layout for the pages to use
    metadata:
      source: 'leadville.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/leadville' # path to the directory of images within `_data`
  photos: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'photos_item' # the layout for the pages to use
    metadata:
      source: 'photos.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/photos' # path to the directory of images within `_data`
  maps:
    output: true
    layout: 'photos_item'
    metadata:
      source: 'maps.csv'
    images:
      source: 'raw_images/maps'
  docs:
    output: true
    layout: 'photos_item'
    metadata:
      source: 'docs.csv'
    images:
      source: 'raw_images/docs'
  climax:
    output: true
    layout: 'photos_item'
    metadata:
      source: 'climax.csv'
    images:
      source: 'raw_images/climax'
  brisbois:
    output: true
    layout: 'photos_item'
    metadata:
      source: 'brisbois.csv'
    images:
      source: 'raw_images/brisbois'
  school:
    output: true
    layout: 'photos_item'
    metadata:
      source: 'school.csv'
    images:
      source: 'raw_images/school'
  tabors:
    output: true
    layout: 'leadville_item'
    metadata:
      source: 'tabors.csv'
    images:
      source: 'raw_images/tabors'
  hale:
    output: true
    layout: 'leadville_item'
    metadata:
      source: 'hale.csv'
    images:
      source: 'raw_images/hale'
  palace:
    output: true
    layout: 'leadville_item'
    metadata:
      source: 'palace.csv'
    images:
      source: 'raw_images/palace'
  cemetery:
    output: true
    layout: 'leadville_item'
    metadata:
      source: 'cemetery.csv'
    images:
      source: 'raw_images/cemetery'

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      leadville:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      photos:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      maps:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      docs:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      climax:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      brisbois:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      school:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      tabors:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      hale:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      palace:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit
      cemetery:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - location
          - label
          - _date
          - object_type
          - current_location
          - keywords
          - caption
          - named_persons
          - source
          - credit

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:  
  - label: 'Exhibits'
    sub:
      - label: 'Inline Parallax Image'
        link: '/exhibits/a/'
      - label: 'Inline Image References'
        link: '/exhibits/b/'
  - label: 'Browse Collections'
    sub:
      - label: 'Leadville'
        link: '/leadville/'
      - label: 'Historic Photos'
        link: '/photos/'
      - label: 'Maps'
        link: '/maps/'
      - label: 'Documents and Books'
        link: '/docs/'
      - label: 'Climax'
        link: '/climax/'
      - label: 'Brisbois Photos'
        link: '/brisbois/'
      - label: 'High Schole Annuals'
        link: '/school/'
      - label: 'The Tabors'
        link: '/tabors/'
      - label: 'Camp Hale'
        link: '/hale/'
      - label: 'Ice Palace'
        link: '/palace/'
      - label: 'Evergreen Cemetery'
        link: '/cemetery/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/awoods'
    - label: 'Contact'
      link: '/contact'
  logos:
    - img: '/img/logo.png'

# FIN
